export const StagePreivews = [
  {
    number: 1,
    date: "SAT. JULY 5",
    distance: "184.9 km",
    type: "FLAT",
    route: "LILLE > LILLE",
    rating: "🛋️🛋️",
    description: `Flat and windy, with just enough northern spice to make the Grand Départ worth watching. A sprinter is gonna be in yellow after this day, and I'm thinking it's Tim.`,
    pick: "TIM MERLIER",
    riderImg: "/riders/tim.png",
    routeImg: "/tdf-routes/1.png",
  },
  {
    number: 2,
    date: "SUN. JULY 6",
    distance: "209.1 km",
    type: "HILLY",
    route: "LAUWIN-PLANQUE > BOULOGNE-SUR-MER",
    rating: "🛋️🛋️🛋️",
    description: `Longest stage of the race, roller coaster from start to finish with 2,550 meters of climbing. Kilometer-long uphill finish, gonna be spicy one!`,
    pick: "JULIAN ALAPHILIPPE",
    riderImg: "/riders/julian.png",
    routeImg: "/tdf-routes/2.png",
  },
  {
    number: 3,
    date: "MON. JULY 7",
    distance: "178.3 km",
    type: "FLAT",
    route: "VALENCIENNES > DUNKERQUE",
    rating: "🛋️🛋️",
    description: `Could be a snooze-fest or a wind-fuelled bonanza. Could go crazy on the Côte de Cassel, but I don’t think it’s hard enough to drop the sprinters.`,
    pick: "JASPER PHILIPSEN",
    riderImg: "/riders/jasper.png",
    routeImg: "/tdf-routes/3.png",
  },
  {
    number: 4,
    date: "TUE. JULY 8",
    distance: "174.2 km",
    type: "HILLY",
    route: "Amiens Métropole > Rouen",
    rating: "🛋️🛋️🛋️",
    description:
      "A baguette stuffed with fireworks, on a twisty descent into the finish in ROUEN. WHos got the biggest balls to drop the rest?",
    riderImg: "/riders/wout.png",
    routeImg: "/tdf-routes/4.png",
    pick: "WOUT VAN AERT",
  },
  {
    number: 5,
    date: "WED. JULY 9",
    distance: "33 km",
    type: "TIME TRIAL",
    route: "Caen > Caen",
    rating: "🛋️🛋️🛋️",
    description:
      "LONG and flat individual time trail, remco got this in the bag, but gc battle starts here!",
    riderImg: "/riders/remco.png",
    routeImg: "/tdf-routes/5.png",
    pick: "REMCO EVENEPOEL",
  },
  {
    number: 6,
    date: "THU. JULY 10",
    distance: "201.5 km",
    type: "HILLY",
    route: "Bayeux > Vire Normandie",
    rating: "🛋️🛋️🛋️🛋️",
    description:
      "Up and down and up and down, probably hardest stage so far and i think its going to the breakway. ",
    riderImg: "/riders/powless.png",
    routeImg: "/tdf-routes/6.png",
    pick: "NEILSON POWLESS",
  },
  {
    number: 7,
    date: "FRI. JULY 11",
    distance: "197 km",
    type: "HILLY",
    route: "Saint-Malo > Mur-de-Bretagne",
    rating: "🛋️🛋️🛋️🛋️🛋️",
    description:
      "REMEMBER WHEN mathieu van der poel won on the Mûr-de-Bretagne in 2021. yeah that shit was legendary, lets run it back again this year. dont miss this stage!",
    riderImg: "/riders/mvdp2.png",
    routeImg: "/tdf-routes/7.png",
    pick: "MATHIEU VAN DER POEL",
  },
];
